name: Build Tinke
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
    - name: Setup VS Dev Environment
  # You may pin to the exact commit or the version.
  # uses: seanmiddleditch/gha-setup-vsdevenv@8c6bbf80998779f2bba87b1452832e561b65fd57
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
      with:
    # Name or path to vswhere.exr
         vswhere: # optional, default is vswhere.exe
    # Target build architecture
         arch: # optional, default is amd64
    # Host architecture (x86, , or amd64)
         host_arch: "x86_amd64" # optional, default is 
    # Overrides the default WinSDK version
         winsdk: # optional, default is 
    # Overrides the default toolset version
         toolset_version: # optional, default is 
    # List of components required in the selected VS installation (semi-colon separated)
         components: # optional, default is Microsoft.VisualStudio.Component.VC.Tools.x86.x64
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Tinke.sln
 
    - name: Build and Publish Web App
      run: msbuild Tinke.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Tinke
        path: bin\Release\Publish
